[project]
name = "a2a"
version = "0.2.0"
description = "A2A Python SDK"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "httpx>=0.28.1",
    "httpx-sse>=0.4.0",
    "mypy>=1.15.0",
    "pydantic>=1.10.13,<2.0.0",
    "sse-starlette>=2.3.3",
    "starlette>=0.46.2",
    "typing-extensions>=4.13.2",
    "uvicorn>=0.34.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
addopts = "--cov=src --cov-config=.coveragerc --cov-report term --cov-report xml:coverage.xml --cov-branch"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = [
    "examples/langgraph",
    "examples/helloworld",
    "examples/google_adk/calendar_agent",
]

[dependency-groups]
dev = [
    "datamodel-code-generator>=0.30.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "pytest-cov>=6.1.1",
    "pytest-mock>=3.14.0",
    "ruff>=0.11.6",
]
